name: CI

"on":
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: bazel
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo -E apt update && sudo -E apt install -y make

    - name: Checkout
      uses: actions/checkout@v5

    # Disabling AppArmor is required to run some tests that use user namespaces.
    - name: Disable AppArmor on the GitHub runner
      uses: cisagov/action-disable-apparmor@437d94f26a2e4bf8c03acfb500a6afc688b497db # v1.0.0

    - name: build
      run: |
          mkdir -p bin
          make unit-tests
          make copy TARGETS=runsc DESTINATION=bin/

    - name: Upload runsc
      uses: actions/upload-artifact@v4
      with:
          name: runsc
          path: bin/runsc
